name: Publish Docker image in DockerHub Registry

on:
  push:
    branches:
      - master

jobs:
  simple:
    name: Push Docker image to DockerHub Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: cowsay.dockerfile
          tags: rw1nkler/public-repo:cowsay
